"""initial_schema

Revision ID: 33cfbd515b20
Revises: 
Create Date: 2026-08-12 00:47:50.727097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33cfbd515b20'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', 'TRANSFER_IN', 'TRANSFER_OUT', name='transactiontype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('families',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_cost_centers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('holder_id', sa.String(length=36), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.Enum('ASSET', 'LIABILITY', name='accounttype'), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('type_identifier', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['holder_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts_payable',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bank', sa.String(length=100), nullable=False),
    sa.Column('agency', sa.String(length=50), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_cards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('issuer', sa.String(length=100), nullable=True),
    sa.Column('due_day', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('limit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('bank_account_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthly_balances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('reference_month', sa.String(length=7), nullable=False),
    sa.Column('projected_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('real_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('source_account_id', sa.String(length=36), nullable=False),
    sa.Column('destination_account_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['destination_account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_instances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('credit_card_id', sa.String(length=36), nullable=False),
    sa.Column('card_holder_id', sa.String(length=36), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['card_holder_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_card_bills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('credit_card_id', sa.String(length=36), nullable=False),
    sa.Column('reference_month', sa.String(length=7), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('previous_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payments_received', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_transfer_settlements',
    sa.Column('bill_id', sa.String(length=36), nullable=False),
    sa.Column('transfer_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['credit_card_bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bill_id', 'transfer_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', 'TRANSFER_IN', 'TRANSFER_OUT', name='transactiontype'), nullable=False),
    sa.Column('accrual_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_forecast', sa.Boolean(), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('card_instance_id', sa.String(length=36), nullable=True),
    sa.Column('credit_card_bill_id', sa.String(length=36), nullable=True),
    sa.Column('transfer_id', sa.String(length=36), nullable=True),
    sa.Column('settled_by_transfer_id', sa.String(length=36), nullable=True),
    sa.Column('originating_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('originating_bill_id', sa.String(length=36), nullable=True),
    sa.Column('source_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('cost_center_id', sa.String(length=36), nullable=True),
    sa.Column('installment_current', sa.Integer(), nullable=False),
    sa.Column('installment_total', sa.Integer(), nullable=False),
    sa.Column('installment_group_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['card_instance_id'], ['card_instances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cost_center_id'], ['family_cost_centers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['credit_card_bill_id'], ['credit_card_bills.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['originating_bill_id'], ['credit_card_bills.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['originating_transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['settled_by_transfer_id'], ['transfers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('bill_transfer_settlements')
    op.drop_table('credit_card_bills')
    op.drop_table('card_instances')
    op.drop_table('wallets')
    op.drop_table('transfers')
    op.drop_table('monthly_balances')
    op.drop_table('credit_cards')
    op.drop_table('bank_accounts')
    op.drop_table('accounts_payable')
    op.drop_table('accounts')
    op.drop_table('members')
    op.drop_table('family_cost_centers')
    op.drop_table('families')
    op.drop_table('categories')
    # ### end Alembic commands ###
